---
- name: Using Roles to configure a cisco router
  gather_facts: False
  hosts: router

  roles:
    - testrole




  /etc/ansible/roles/testrole/tasks/main.yml

  ---
  - name: Configure DHCP server
    ios_config:
      src: /root/config/config.txt




  /root/config/config.txt


  ip dhcp excluded-address 192.168.30.1
  !
  ip dhcp pool TEST1
   network 192.168.30.0 255.255.255.0
   default-router 192.168.30.1
  !
  int lo0
   ip add 1.1.1.1 255.255.255.0
  !
  int e0/3
   ip add 3.3.3.3 255.255.255.0
   no shut