


      MAIN PLAYBOOK 
---
- name: Using template to configure cisco router
  hosts: router

  roles:
    - testtemplate



    /etc/ansible/roles/testtemplate/tasks/main.yml

---
- name: Configure DHCP
  template: src=testtemplate1.j2 dest=/root/config 







  /etc/ansible/roles/testtemplate/templates/testtemplate1.j2

  ip dhcp excluded-address 192.168.30.1
  !
  ip dhcp pool TEST1
   network 192.168.30.0 255.255.255.0
   default-router 192.168.30.1
  !
  int lo0
   ip add 1.1.1.1 255.255.255.0
  !
  int e0/3
   ip add 3.3.3.3 255.255.255.0
   no shut

